services:
  app:
    container_name: soundade
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}:/data
    env_file:
      - .env
    tty: true
    stdin_open: true
