services:
  app:
    container_name: soundade
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /mnt/echodata/nature_sense/Nature_Sense/Raw_Data:/data
    env_file:
      - .env
    tty: true
    stdin_open: true
