services:
  app:
    container_name: soundade
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}:/data
      - ${SAVE_PATH}:/results
      - ${CONFIG_PATH}:/config.yml
    env_file:
      - .env
    tty: true
    stdin_open: true
    command: uv run main.py pipeline
