name: soundade
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - cython>=0.29.*
  - dask>=2022.7.0
  - fastparquet>=0.8.*
  - ffmpeg>=5.1.*
  - findiff>=0.10.*
  - joblib>=1.1.*
  - libarrow>=10.*
  - librosa>=0.9.*
  - libsndfile>=1.0.*
  - matplotlib>=3.5.*
  - pandas>=1.5.*
  - pip>=22.2.*
  - pyarrow>=10.*
  - pykml>=0.2.*
  - pysoundfile>=0.10.*
  - python>=3.9.*
  - resampy>=0.4.*
  - seaborn>=0.12.*
  - jupyter>=1.0.*
  - numpy>=1.22.*
  - pandas>=1.4.*
  - scikit-image>=0.19.*
  - scikit-learn>=1.1.*
  - scipy>=1.7.*
  - seaborn>=0.12
  - statsmodels>=0.13.*
  - pip:
    - astral>=3.2
    - colorednoise>=2.1.*
    - dask-jobqueue>=0.8.1
    - findiff>=0.9.2
    - lempel-ziv-complexity>=0.2.*
    - pandas-path==0.3.*
    - scikit-maad>=1.3.*
    - tqdm>=4.64.*
    - tqdm-joblib>=0.0.*
#    - git+https://github.com/pranaysy/ETCPy.git

