name: Cairngorms
pattern: >(?P<recorder_model>[^/]+)/(?P<site_level_1>[^/]+)/\d{4}/\d{2}/(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})\.[wav|flac|mp3]
sample_rate: 32_000
frame_length: 1_536
hop_length: 768
n_fft: 1_536
min_conf: 0.0
segment_duration: 60.0
