name: Kilpisjarvi
pattern: >
  (?P<site_level_1>[^/_]+)(?:_\d+)?/
  Data/
  (?P<recorder>SMA\d{5})_
  (?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_
  (?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})
  \.[wav|flac|mp3]
sample_rate: 24_000
frame: 1_024
hop: 256
n_fft: 1_024
min_conf: 0.0
segment_duration: 60.0
