name: Kilpisjarvi
pattern: (?P<site_level_1>[^/_]+)(?:_\d{1})?(?:/Data)?/(?P<recorder>SMA\d{5})_(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})(?P<second>\d{2})\.[wav|flac|mp3]+
sample_rate: 24_000
frame_length: 1_024
hop_length: 512
n_fft: 1_024
min_conf: 0.0
segment_duration: 60.0
bi_flim: [2000, 8000]
aei_flim: [0, 20000]
aei_bin_step: 500
aei_db_threshold: -47
