name: SoundingOutChorus
pattern: (?P<site_level_1>[^/]+)/(?P<site_level_2>[^/]+)/(?P<site_level_3>[^/]+)/(?P<recorder_name>[A-Z]{2}-[0-9]{2})_(?P<channel>[0-9])_(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})\.(?i:wav|flac|mp3)
sample_rate: 48_000
frame_length: 2_048
hop_length: 1024
n_fft: 2_048
segment_duration: 60.0
min_conf: 0.0
R_compatible: true
