name: SoundingOut
pattern: (?P<site_level_1>[^/]+)/(?P<site_level_2>[^/]+)/[A-Z]+[_]?(?P<site_level_3>\d{2})/Data_\d{1}/[A-Z]+-(?P<recorder>[0-9]{2})_(?P<channel>[0-9])_(?P<year>\d{4})(?P<month>\d{2})(?P<day>\d{2})_(?P<hour>\d{2})(?P<minute>\d{2})\.(?i:wav|flac|mp3)
sample_rate: 48_000
frame_length: 2_048
hop_length: 512
n_fft: 2_048
segment_duration: 60.0
min_conf: 0.0
